config/routes.rb
Rails.application.routes.draw do
  root      'home#index'

  # Json Resources
  resources :articles, only: [:create, :index, :destroy, :update]
  resources :comments, only: [:create, :index, :destroy]

  # Admin Section
  get       'admin'   => 'admin#admin'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

  # sends a token through the bcrypt system to see if a user is authenticated
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :author,      presence: true
  validates :content,     presence: true
  validates :article_id,  presence: true

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :logged_in_user

  def admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update]
  respond_to :json

  def index
    respond_with Article.all.includes(:comments).reverse_order.to_json(include: [:comments])
  end

  def create
    respond_with Article.create!(article_params)
  end

  def update
    respond_with Article.find(params[:id]).update!(article_params)
  end

  def destroy
    respond_with Article.find(params[:id]).destroy
  end

  private
  def article_params
    params.require(:article).permit(:id, :title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:destroy]
  respond_to :json

  def index
    respond_with Comment.all.includes(:article).to_json(include: [:article])
  end

  def create
    respond_with Comment.create!(comment_params)
  end

  def destroy
    respond_with Comment.find(params[:id]).destroy
  end

  private
    def comment_params
      params.require(:comment).permit(:author, :content, :article_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = Admin.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Successfully Logged In'
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # returns current user
  def current_user
    @current_user ||= Admin.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # helper for logged in user
  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please Log In'
      redirect_to login_url
    end
  end

  # checks if current user is the user argument
  def current_user?(user)
    user == current_user
  end


end

app/views/admin/admin.html.erb
<div class="main admin">
	<%= react_component('AdminArticleContainer') %>
	<%= react_component('AdminCommentContainer') %>
</div>

app/views/home/index.html.erb
<h1>A Simple Blog</h1>

<div class="main">
	<%= react_component('ArticleContainer') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riipen Demo</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/marked/0.3.2/marked.min.js"></script>
</head>
<body>

<% if logged_in? %>
	<ul id="adminNav">
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'Admin', admin_path %></li>
		<li><%= link_to 'Sign Out', logout_path, method: :delete %></li>
	</ul>
<% else %>
	<ul id="adminNav">
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'About Me', 'http://www.colinw.info' %></li>
		<li><%= link_to 'Login', login_path %></li>
	</ul>
<% end %>

<%= yield %>

</body>
</html>